### ISSUE TITLE
Adding language skills to Gotchis 

### ISSUE THREAD

**Issue by ferhatsirin77** [aavegotchi/aavegotchi-wiki#166]
Hello as there is no discussion forum I place it here. 

I suggest to add language option to their character. So we just do not come and pet and learn something daily and interact. 
Maybe artificial intelligence language skills or just basic style language learning program from A1 to C2 level so after spending time with them we can learn English, German, French, Russian etc. etc. people may send more time on the site and connected more to gotchis learning daily is medicine. So they maybe skilled from A1 to C level of multiple languages. 

What do you think about that idea? 

If you like and use my idea reward me with some GHST please. Thanks...

**Comment by cinnabarhorse** [comment]
Hi fren, there's a forum to discuss proposals like this on https://dao.aavegotchi.com. You can get a conversation started there!
