### ISSUE TITLE
Link Marine set is missing from wearable sets page

### ISSUE THREAD

**Issue by mikey-jay** [aavegotchi/aavegotchi-wiki#334]
The Link Marine set is missing from the wearables sets page. Here is the correct on-chain data according to  https://www.aadventure.io/wearable-sets/all

Set: Link Marine
Items: Link White Hat, Link Mess Dress, Link Bubbly
Set Bonuses: BRS +4, AGG +2, BRN +4

**Comment by Unintelligent-Nerd** [comment]
The same set already exists in the wiki as "General." Let me confirm with Coderdan before pushing updates. Thanks fren!

**Comment by mikey-jay** [comment]
> The same set already exists in the wiki as "General." Let me confirm with Coderdan before pushing updates. Thanks fren!

Ahhh... I see! Weird that It appears to shows up as both "Link Marine" and "General" on-chain (or at least in the subgraph). Not sure if adding it to the wiki is strictly necessary then. Or maybe just an "aka Link Marine"?

**Comment by Unintelligent-Nerd** [comment]
@mikey-jay I've confirmed with Coderdan that the official name for the set is "Link Marine." Have updated the wiki accordingly

Thanks fren!
